version: '3'

services:
  app:
    build: 
      context: .
      dockerfile: Dockerfile
    container_name: app
    expose:
      - "3000"
    volumes:
      - ./:/var/www
    networks:
      - network-desafio-indt

  nginx:
    image: nginx:1.23.2-alpine
    container_name: nginx
    restart: unless-stopped
    tty: true
    volumes:
      - ./:/var/www
      - ./.docker/nginx/conf.d/:/etc/nginx/
    ports:
      - "8080:80"
    depends_on:
      - app
    networks:
      - network-desafio-indt
  
  mysql:
    image: mysql:5.7
    container_name: mysql
    command: --sql-mode=""
    restart: unless-stopped
    tty: true
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
      - ./.docker/mysql/my.cnf:/etc/mysql/my.cnf
    environment:
      MYSQL_ROOT_PASSWORD: 2@y~(!FlM_B72S(
    networks:
      - network-desafio-indt

networks:
  network-desafio-indt:
    driver: bridge

volumes:
  db_data:
    driver: local