version: '3'

services:
  app:
    build: 
      context: .
      dockerfile: Dockerfile
    container_name: app
    expose:
      - "3000"
    volumes:
      - ./:/var/www

  nginx:
    image: nginx:1.23.2-alpine
    container_name: nginx
    restart: unless-stopped
    tty: true
    volumes:
      - ./:/var/www
      - ./.docker/nginx/conf.d/:/etc/nginx/
    ports:
      - "8080:80"
    depends_on:
      - app

networks:
  default:
    external: true
    name: nginx-proxy-manager